# Generated by Django 5.2.13 on 2026-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(default="your article was great...."),
        ),
    ]
