# Generated by Django 5.2.13 on 2026-09-17 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="views",
        ),
        migrations.AddField(
            model_name="article",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
