# Generated by Django 5.2.13 on 2026-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_remove_article_views_article_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
